### ISSUE TITLE
BME280

### ISSUE THREAD

**Issue by Walter-DL2OL** [richonguzman/LoRa_APRS_iGate#73] opened 2024-04-12 18:24 UTC
Hello Ricardo, where can I enter the height correction in the iGate?
Greetings Walter

**Comment by richonguzman** [comment] 2024-04-12 19:21
soon we will add this also also temperature correction as well

**Comment by SQ2CPA** [comment] 2024-04-16 19:41
Duplicate of https://github.com/richonguzman/LoRa_APRS_iGate/issues/10

**Closed** 2024-04-16 19:45 UTC
