### ISSUE TITLE
Option to send battery voltage as telemetry.

### ISSUE THREAD

**Issue by gbecki** [richonguzman/LoRa_APRS_iGate#26] opened 2024-01-25 11:32 UTC
Hey Ricardo!

Is it possible to have an extra option to send battery voltage via telemetry to APRS-IS servers?

Thank you

PU5KNB - Guilherme

**Comment by richonguzman** [comment] 2024-01-25 12:44
Hello

Yes it can be done , will be updating a few things before this.

Just to be sure , is this to replace sending this info as comment?

**Comment by simontorres** [comment] 2024-01-25 13:11
Hi @gbecki @richonguzman I was wondering the same. I'm using a 3S LiPo battery with a 12v to USB converter (those sold for cars) so the value reported is actually the value at the USB input. I don't want to get off-topic but since the issue is rather broad I'll just ask.

I have one of these modules that are usually used for RC planes or drones, if I'm not mistaken they even can cut the power since those LiPo batteries are quite sensitive to discharge. Provided that I have a device or circuit to monitor a multi-cell lipo battery (3 in my case) the question is: Can I send it all three cells voltages as metadata? 
![3DR-current-sensor-top](https://github.com/richonguzman/LoRa_APRS_iGate/assets/3878895/f375f11f-7913-4046-9315-03655bf420cb)

Are there enough analog input pins available to monitor each cell individually? or it would require some external serialization?

Simon - CD2STW

**Comment by richonguzman** [comment] 2024-01-25 13:32
Hi Simon,

Right now the igate has 1 "extra" pin labeled to work as external voltage value input.

Sure we can add more for using those 3 voltages (each with his own voltage divider for this)

Is this what you need?

**Comment by simontorres** [comment] 2024-01-25 13:45
Hi Ricardo,

Yes!, exactly. However, it would be interesting to know how many people will want such a feature, to be honest those batteries would not be my first choice as they require extra care but I was given them to work with. On the positive side they have good capacity-to-weight ratio, so, provided you have all the necessary care they are excellent. 

Saludos

**Comment by gbecki** [comment] 2024-01-25 15:29
> Hello
> 
> Yes it can be done , will be updating a few things before this.
> 
> Just to be sure , is this to replace sending this info as comment?

Sending as comment is a nice feature too. But you can do both?

Take your time,

Un saludo,

Guilherme

**Comment by richonguzman** [comment] 2024-01-31 15:26
gbecki, please remember me this in two weeks or so as I'm vacations and also finishing a 4G/LTE igate version and will be coming back to this

**Comment by Szetya** [comment] 2024-03-04 12:24
> Hey Ricardo!
> 
> Is it possible to have an extra option to send battery voltage via telemetry to APRS-IS servers?
> 
> Thank you
> 
> PU5KNB - Guilherme

Did you have something similar in mind? https://aprs.fi/info/a/HA5SZI-10

**Comment by richonguzman** [comment] 2024-03-04 21:43
we could add this too , but first it has to be defined how many or what values should be sended, because we cant add 1000 more variables to be selected over WebUI, right?

**Comment by xe2mbe** [comment] 2024-04-18 02:20
Hi Ricardo,

I'm currently testing a LoRa Igate configured as a digipeater (xe2mbe-2). During my testing, I noticed that it doesn't send telemetry data. Could you please include sending telemetry data when it's configured as a digipeater? This telemetry data is essential as it allows us to monitor the battery status, especially in locations where there is no electrical power and solar panels with batteries are used instead.

**Comment by richonguzman** [comment] 2024-04-18 02:55
> Hi Ricardo,
> 
> I'm currently testing a LoRa Igate configured as a digipeater (xe2mbe-2). During my testing, I noticed that it doesn't send telemetry data. Could you please include sending telemetry data when it's configured as a digipeater? This telemetry data is essential as it allows us to monitor the battery status, especially in locations where there is no electrical power and solar panels with batteries are used instead.

Hi,

do you have:
-digiMode active in WIDE1-1 ??
-LoRa Tx enabled?
-Send Beacon over RF enabled?
-Wx data enabled?

**Comment by xe2mbe** [comment] 2024-04-19 03:23
Dear Ricardo,

I have reviewed the Digi settings following your instructions, and all parameters appear to be correctly configured. I have attached some pictures for your reference.

Our topology consists of an i-gate connected to the Internet and enabled to connect to the APRS-IS server. Additionally, we have another card configured as a Digi. The issue we're encountering is that the Digi is sending the telemetry data as comments. I believe this is the reason why the telemetry is not being decoded correctly, as it does not have the correct format.

Could you please advise on how to rectify this issue so that the telemetry data can be decoded as intended?

Thank you for your assistance.

Best regards,

![imagen](https://github.com/richonguzman/LoRa_APRS_iGate/assets/16530404/4f62576c-c6c0-426e-87a8-d9fe0929bccc)
![imagen](https://github.com/richonguzman/LoRa_APRS_iGate/assets/16530404/6edcc75f-fd5f-4fe7-9968-523c9908eb06)
![imagen](https://github.com/richonguzman/LoRa_APRS_iGate/assets/16530404/4ca8f57e-1410-4d93-ba23-eb32233761de)
This picture shows that telemetry is sending as comment:
![imagen](https://github.com/richonguzman/LoRa_APRS_iGate/assets/16530404/e053ccbd-caf4-4db0-9bd1-d5373a56028f)
When I enable the APRS-IS to the Digipeater the telemetry is well decoded:
![imagen](https://github.com/richonguzman/LoRa_APRS_iGate/assets/16530404/73b339f9-0301-4c95-af58-a2fa89844e6c)

**Comment by richonguzman** [comment] 2024-04-19 03:34
Hola!

can you download the latest latest version of iGate (V1.0.2) as this should be fixed in newer version of the igate: default symbols for sending Wx data

**Comment by xe2mbe** [comment] 2024-04-19 04:45
> Hola!
> 
> can you download the latest latest version of iGate (V1.0.2) as this should be fixed in newer version of the igate: default symbols for sending Wx data

Listo... ya funcionó.... 73 buena noche

**Comment by richonguzman** [comment] 2024-04-19 13:36
> > Hola!
> > can you download the latest latest version of iGate (V1.0.2) as this should be fixed in newer version of the igate: default symbols for sending Wx data
> 
> Listo... ya funcionó.... 73 buena noche

genial!!!

**Closed by richonguzman** 2024-04-19 13:36 UTC
